### ISSUE TITLE
Unresolved Eigen error

### ISSUE THREAD

**Issue by antithing** [zha0ming1e/LEGO#1]
Hi, and thank you for making this code available. i am trying to build it on windows, with visual studio.

the base lib builds great, but the slam lib gives me this error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "class Eigen::Matrix<double,3,1,0,3,1> G" (?G@@3V?$Matrix@N$02$00$0A@$02$00@Eigen@@A) referenced in function "public: virtual void __cdecl lego::EdgeIMU::computeJacobians(void)" (?computeJacobians@EdgeIMU@lego@@UEAAXXZ)	slam	D:\testing\LEGO\LEGO-main\built\lego\slam\edge_imu.obj	1	
```

I can't figure out what this is. Do you have any ideas? Thanks!

**Comment by zha0ming1e** [comment]
Hi, thank you for testing the code. I'm sorry that I'm not familiar with Windows OS. This code is only tested on Ubuntu 18.04. Maybe you need to change something in CMakeLists.txt files, but I'm not sure. ：）

**Comment by antithing** [comment]
Ah okay, thanks. It is weird! I cannot figure this out. The class it is looking for doesn't seen to be referenced in the code at all.

**Comment by zha0ming1e** [comment]
The Eigen version on my computer is 3.3.4 and actually you can rewrite the classes under [*slam*](https://github.com/zha0ming1e/LEGO/tree/main/lego/slam) directory.

**Comment by antithing** [comment]
Hi sorry to keep bothering you. When i run the code as is, i get :

`unresolved external symbol "class Eigen::Matrix<double,3,1,0,3,1> G"
`
when I add:

`class Eigen::Matrix<double, 3, 1, 0, 3, 1> G;
`
to eigen_types.h, I get the error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2005	"class Eigen::Matrix<double,3,1,0,3,1> lego::G" (?G@lego@@3V?$Matrix@N$02$00$0A@$02$00@Eigen@@A) already defined in edge_imu.obj	

```

Do you have any thoughts on what might be happening here?
